version: '3.9'
services:
  app:
    build: .
    environment:
      - PORTFOLIO_SMTP_USER=${PORTFOLIO_SMTP_USER}
      - PORTFOLIO_SMTP_PASS=${PORTFOLIO_SMTP_PASS}
      - DEPLOY_ENV=local # 本番時は production に変更
    ports:
      - "8080:8080"
    volumes:
      # ホスト側のパス : コンテナ内の固定パス
      # ローカル開発時はここを C:/MyAppData/portfolio_images に
      # ローカルデプロイ時はここを C:/MyAppData/portfolio_images:/img_mountに
      # 本番デプロイ時はここを /var/www/portfolio/img/profile に書き換えます
      - C:/MyAppData/portfolio_images:/img_mount
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

